### ISSUE TITLE
Remove the site title if a custom header is used?

### ISSUE THREAD

**Issue by elbsurfer** [billerickson/EA-Genesis-Child#92]
Hello,
I use a custom header, introduced with this option:

`add_theme_support( 'genesis-custom-header', array( 'width' => 600, 'height' => 135 ) );`

Then I go into the customizer, select an image (here the basic genesis image) and also deselect the checkbox that is used to show the site-title / subheadline in the header, but still the site-title is shown overlaying on the header image. Is this option not supported in your child theme? https://d.pr/i/8U26HY

**Comment by billerickson** [comment]
I've never used `genesis-custom-header` or that checkbox. It does not look like this theme has support for that. 

I would've assumed if Genesis added a checkbox to disable the header title/description, then Genesis core would handle the removal of the title/description. It shouldn't be something a child theme must add support for.

If you provide a pull request to add support I'll review and test it.

**Comment by elbsurfer** [comment]
I checked it, and the only reason why the title still appears is, because the genesis parent style is not included and because of that, this CSS rule is missing: https://d.pr/i/2T47Zw

**Comment by billerickson** [comment]
I've made a note of how to add custom header support to the wiki: https://github.com/billerickson/EA-Genesis-Child/wiki

I'm closing this issue as the base theme does not support custom headers out of the box.
