### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by lwangdu** [billerickson/EA-Genesis-Child#93]
Hi Bill,
I just downloaded your EA-Genesis-Child from your GitHub. Looks like they is duplicate property in your stylesheet. Path: assets/css/editor-style.css
line:
159 -webkit-text-decoration: underline dotted;
150          text-decoration: underline dotted;

Is that correct?  Thank you for your great website that is amazing for WordPress community.

Thank you,

Lobsang

**Comment by billerickson** [comment]
Thanks for the kind comments.

I believe that's my auto-prefixer adding webkit support. I'm not sure why it needs webkit support for text decoration, and it could probably be omitted, but the auto-prefixer helps with more modern CSS properties. 

If you look in the actual source files (in /scss) you'll see `-webkit-text-decoration` is not located in there. 

If you're writing the CSS yourself, you can definitely omit that. But I'm not going to muck around with my code compiler's auto-prefixer :)
