### ISSUE TITLE
Is this comment markup really correct?

### ISSUE THREAD

**Issue by codegrau** [billerickson/EA-Genesis-Child#94]
Hey @billerickson , great start theme - thank you for this! 

I stumbled upon this comment markup with your child theme and was wondering, if this really is the correct markup order for time, time-link and comment-meta. Besides: what would you expect inside the p.comment-meta tag?

````
<header class="comment-header">
  <p class="comment-author">
   <span class="comment-author-name" itemprop="name">TestUser</span>
   <span class="says">says</span>
 </p>
  <a class="comment-time-link" href="//wordpress.test:8000/306-2/#comment-14">10.05.19 at 23:34</a>
  <time class="comment-time" datetime="2019-05-10T23:34:29+02:00"></time>
  <p class="comment-meta"></p>
</header>
````

Looking forward to hear from you!

**Comment by billerickson** [comment]
Thanks for the question.

That actually appears to be an issue with Genesis core. My child theme isn't customizing the comment output in any way, and when I switch the active theme to Genesis I see the same issue.

I'll post this issue in the Genesis GitHub repo so it can hopefully be resolved in the next update.
