### ISSUE TITLE
Undefined mixin media

### ISSUE THREAD

**Issue by Trenbania** [billerickson/EA-Genesis-Child#96]
Not sure if this is a bug or my setup (probably the latter)!

I've installed the theme on a test site so that I can play around and learn SASS. I'm using WP-SCSS to compile and it appears to be setup correctly.

However, I'm getting fatal errors:

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /srv/.../wp-content/plugins/wp-scss/scssphp/src/Compiler.php on line 1328

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /srv/.../wp-includes/class-wp-recovery-mode.php on line 169

These disappear if I remove _include-media.scss

I have little knowledge of SASS and that probably shows!

**Comment by billerickson** [comment]
Hmm, that's strange. I've never used WP-SCSS before, but I've used `_include-media` on hundreds of projects. You might try posting a support request on that plugin's WP.org support forum asking about it.

If removing the `_include-media.scss` reference fixes it, that means it's likely that WP-SCSS is loading its own version of `_include-media.scss` or something similar. You should get a message saying the media mixin is undefined.

If you can't figure it out, you could remove `_include-media.scss` and change every instance of `@include media()` to a normal media query (ex:  `@media only screen and (min-width: 768px)`)
